#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
FORCE=0

if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
elif [[ $# -gt 0 ]]; then
  echo "Usage: $0 [--force]" >&2
  exit 2
fi

if [[ ! -t 0 ]]; then
  echo "init-config.sh is interactive and requires a terminal." >&2
  exit 1
fi

if [[ -e "${ENV_FILE}" && ${FORCE} -ne 1 ]]; then
  echo "${ENV_FILE} already exists. Use --force to replace it." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required." >&2
  exit 1
fi

random_secret() {
  openssl rand -hex 32
}

prompt_value() {
  local variable="$1"
  local prompt="$2"
  local default_value="${3:-}"
  local value=""

  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt} [${default_value}]: " value
    value="${value:-${default_value}}"
  else
    while [[ -z "${value}" ]]; do
      read -r -p "${prompt}: " value
    done
  fi

  printf -v "${variable}" '%s' "${value}"
}

LOCAL_IP=""
if command -v ip >/dev/null 2>&1; then
  LOCAL_IP="$(ip route get 1.1.1.1 2>/dev/null | awk '{ for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit } }' || true)"
fi

cat <<'EOF'
XMPP Portainer Stack configuration

You need working DNS records and a public IPv4 (directly or via NAT).
Secrets are generated automatically and written only to .env.
EOF

echo
prompt_value XMPP_DOMAIN "Main XMPP domain (for example xmpp.example.org)"
while [[ ! "${XMPP_DOMAIN}" =~ ^[A-Za-z0-9.-]+$ ]]; do
  echo "Invalid domain syntax." >&2
  prompt_value XMPP_DOMAIN "Main XMPP domain"
done

prompt_value LE_EMAIL "Let's Encrypt email"
while [[ "${LE_EMAIL}" =~ [[:space:]=] || "${LE_EMAIL}" != *@* ]]; do
  echo "Enter a simple email address without spaces." >&2
  prompt_value LE_EMAIL "Let's Encrypt email"
done

prompt_value TURN_EXTERNAL_IP "Public IPv4 address used by NAT/TURN"
prompt_value TURN_LISTEN_IP "Local IP on which coturn listens" "${LOCAL_IP}"
prompt_value TURN_RELAY_IP "Local TURN relay IP" "${TURN_LISTEN_IP}"
prompt_value XMPP_ADMIN_USER "XMPP administrator username" "admin"
prompt_value ADMIN_HTTP_USER "HTTP Basic Auth username for /admin" "admin"

for username in "${XMPP_ADMIN_USER}" "${ADMIN_HTTP_USER}"; do
  if [[ ! "${username}" =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "Administrator usernames may contain only letters, digits, dot, underscore and dash." >&2
    exit 1
  fi
done

XMPP_ADMIN_PASSWORD="$(random_secret)"
ADMIN_HTTP_PASSWORD="$(random_secret)"
POSTGRES_PASSWORD="$(random_secret)"
TURN_SECRET="$(random_secret)"

TMP_ENV="$(mktemp)"
trap 'rm -f "${TMP_ENV:-}"' EXIT

cat > "${TMP_ENV}" <<EOF
# Generated by scripts/init-config.sh
XMPP_DOMAIN=${XMPP_DOMAIN}
XMPP_ADMIN_USER=${XMPP_ADMIN_USER}
XMPP_ADMIN_PASSWORD=${XMPP_ADMIN_PASSWORD}

ADMIN_HTTP_USER=${ADMIN_HTTP_USER}
ADMIN_HTTP_PASSWORD=${ADMIN_HTTP_PASSWORD}
ADMIN_HTPASSWD_FILE=/etc/nginx/.htpasswd-xmpp-admin

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

LE_CERT_NAME=${XMPP_DOMAIN}
LE_EMAIL=${LE_EMAIL}
CERT_SOURCE_DIR=/var/lib/xmpp-portainer-stack/certs

TURN_SECRET=${TURN_SECRET}
TURN_SECRET_FILE=/var/lib/xmpp-portainer-stack/turn-secret
TURN_CONFIG_FILE=/var/lib/xmpp-portainer-stack/turnserver.conf
TURN_LISTEN_IP=${TURN_LISTEN_IP}
TURN_RELAY_IP=${TURN_RELAY_IP}
TURN_EXTERNAL_IP=${TURN_EXTERNAL_IP}
TURN_MIN_PORT=49160
TURN_MAX_PORT=49200
EOF

chmod 0600 "${TMP_ENV}"
mv -f "${TMP_ENV}" "${ENV_FILE}"
trap - EXIT
chmod 0600 "${ENV_FILE}"

echo
echo "Created ${ENV_FILE} with mode 0600."
echo "Generated independent secrets for XMPP admin, nginx Basic Auth, PostgreSQL and TURN."
echo
echo "Next steps:"
echo "  1. Verify DNS and NAT/port forwarding."
echo "  2. sudo ./scripts/setup-host.sh"
echo "  3. docker compose up -d --pull always"
echo "  4. sudo ./scripts/doctor.sh"
